# Generated by Django 5.1 on 2026-01-01 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedModelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_file', models.FileField(upload_to='uploaded_models/')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.PositiveIntegerField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('model_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
